xz/list.h File Reference
List information about .xz files.
Functions
void list_file (const char *filename)
List information about the given .xz file.
void list_totals (void)
Show the totals after all files have been listed.
Detailed Description
List information about .xz files.
Function Documentation
void list_file (const char * filename)
List information about the given .xz file.
References xz_file_info::idx, io_close(), io_open_src(), lzma_index_end(), message_error(), message_fatal(), message_filename(), message_verbosity_get(), opt_format, parse_indexes(), and V_WARNING.
void list_totals (void)
Show the totals after all files have been listed.
References message_verbosity_get(), totals, and V_WARNING.