xz/options.h File Reference
Parser for filter-specific options.
Functions
lzma_options_delta * options_delta (const char *str)
Parser for Delta options.
lzma_options_bcj * options_bcj (const char *str)
Parser for BCJ options.
lzma_options_lzma * options_lzma (const char *str)
Parser for LZMA options.
Detailed Description
Parser for filter-specific options.
Function Documentation
lzma_options_delta* options_delta (const char * str)
Parser for Delta options.
Returns
Pointer to allocated options structure. Doesn't return on error.
References parse_options(), lzma_options_delta::type, and xmalloc.
lzma_options_bcj* options_bcj (const char * str)
Parser for BCJ options.
Returns
Pointer to allocated options structure. Doesn't return on error.
References parse_options(), lzma_options_bcj::start_offset, and xmalloc.
lzma_options_lzma* options_lzma (const char * str)
Parser for LZMA options.
Returns
Pointer to allocated options structure. Doesn't return on error.
References lzma_options_lzma::lc, lzma_options_lzma::lp, lzma_lzma_preset(), LZMA_MF_BT2, LZMA_MF_BT3, LZMA_MF_BT4, LZMA_MF_HC3, LZMA_MF_HC4, LZMA_MODE_FAST, LZMA_MODE_NORMAL, LZMA_PRESET_DEFAULT, message_bug(), message_fatal(), lzma_options_lzma::mf, lzma_options_lzma::nice_len, parse_options(), and xmalloc.