lzmainfo/lzmainfo.c File Reference
lzmainfo tool for compatibility with LZMA Utils
#include `sysdefs.h`
*
#include <stdio.h>
*
#include <errno.h>
*
#include `lzma.h`
*
#include `getopt.h`
*
#include `tuklib_gettext.h`
*
#include `tuklib_progname.h`
*
#include `tuklib_exit.h`
*
Functions
static void lzma_attribute ((__noreturn__))
static void parse_args (int argc, char **argv)
Parse command line options.
static uint32_t my_log2 (uint32_t n)
Primitive base-2 logarithm for integers.
static bool lzmainfo (const char *name, FILE *f)
Parse the .lzma header and display information about it.
int main (int argc, char **argv)
Detailed Description
lzmainfo tool for compatibility with LZMA Utils
Function Documentation
static void parse_args (int argc, char ** argv) [static]
Parse command line options.
static uint32_t my_log2 (uint32_t n) [static]
Primitive base-2 logarithm for integers.
Referenced by lzmainfo().
static bool lzmainfo (const char * name, FILE * f) [static]
Parse the .lzma header and display information about it.
References lzma_options_lzma::dict_size, lzma_filter::id, lzma_options_lzma::lc, lzma_options_lzma::lp, LZMA_FILTER_LZMA1, LZMA_MEM_ERROR, LZMA_OK, LZMA_OPTIONS_ERROR, lzma_properties_decode(), my_log2(), lzma_filter::options, and lzma_options_lzma::pb.