xz/coder.h File Reference
Compresses or uncompresses a file.
Enumerations
enum operation_mode { MODE_COMPRESS,
MODE_DECOMPRESS,
MODE_TEST,
MODE_LIST
 }
enum format_type { FORMAT_AUTO,
FORMAT_XZ,
FORMAT_LZMA,
FORMAT_RAW
 }
Functions
void coder_set_check (lzma_check check)
Set the integrity check type used when compressing.
void coder_set_preset (uint32_t new_preset)
Set preset number.
void coder_set_extreme (void)
Enable extreme mode.
void coder_add_filter (lzma_vli id, void *options)
Add a filter to the custom filter chain.
void coder_set_compression_settings (void)
void coder_run (const char *filename)
Compress or decompress the given file.
void coder_free (void)
Free the memory allocated for the coder and kill the worker threads.
Variables
enum operation_mode opt_mode
enum format_type opt_format
bool opt_auto_adjust
bool opt_single_stream
If true, stop after decoding the first stream.
uint64_t opt_block_size
Detailed Description
Compresses or uncompresses a file.
Function Documentation
void coder_set_check (lzma_check check)
Set the integrity check type used when compressing.
References check, and check_default.
void coder_set_preset (uint32_t new_preset)
Set preset number.
References filters_count, lzma_filter::options, and preset_number.
void coder_set_extreme (void)
Enable extreme mode.
References preset_extreme.
void coder_add_filter (lzma_vli id, void * options)
Add a filter to the custom filter chain.
References filters_count, id, lzma_filter::id, LZMA_FILTERS_MAX, message_fatal(), and lzma_filter::options.
void coder_run (const char * filename)
Compress or decompress the given file.
References lzma_stream::avail_in, coder_init(), coder_normal(), coder_passthru(), io_close(), io_open_dest(), io_open_src(), io_read(), message_filename(), message_progress_end(), message_progress_start(), lzma_stream::next_in, opt_mode, file_pair::src_st, and user_abort.
void coder_free (void)
Free the memory allocated for the coder and kill the worker threads.
References lzma_end().
Variable Documentation
enum operation_mode opt_mode
Operation mode of the command line tool. This is set in args.c and read in several files.
Referenced by coder_init(), coder_normal(), coder_run(), message_filename(), message_mem_needed(), print_filename(), progress_pos(), and suffix_get_dest_name().
enum format_type opt_format
File format to use when encoding or what format(s) to accept when decoding. This is a global because it's needed also in suffix.c. This is set in args.c.
Referenced by coder_init(), coder_normal(), compressed_name(), list_file(), and uncompressed_name().
bool opt_auto_adjust
If true, the compression settings are automatically adjusted down if they exceed the memory usage limit.
bool opt_single_stream
If true, stop after decoding the first stream.
Referenced by coder_init(), and coder_normal().
uint64_t opt_block_size
If non-zero, start a new .xz Block after every opt_block_size bytes of input. This has an effect only when compressing to the .xz format.
Referenced by coder_normal().