liblzma/common/filter_flags_decoder.c File Reference
Decodes a Filter Flags field.
#include `filter_decoder.h`
*
Functions
lzma_ret lzma_filter_flags_decode (lzma_filter *filter, lzma_allocator *allocator, const uint8_t *in, size_t *in_pos, size_t in_size)
Decode Filter Flags from given buffer.
Detailed Description
Decodes a Filter Flags field.
Function Documentation
lzma_ret lzma_filter_flags_decode (lzma_filter * filter, lzma_allocator * allocator, const uint8_t * in, size_t * in_pos, size_t in_size)
Decode Filter Flags from given buffer.
The decoded result is stored into *filter. The old value of filter->options is not free()d.
Returns
- LZMA_OK
LZMA_OPTIONS_ERROR
LZMA_MEM_ERROR
LZMA_PROG_ERROR
References LZMA_DATA_ERROR, LZMA_FILTER_RESERVED_START, lzma_properties_decode(), lzma_vli_decode(), and return_if_error.
Referenced by lzma_block_header_decode().